### PR TITLE
docs: illustrate transitions

### PR DESCRIPTION
**Pull request by wiese**
Bug: [T256859](https://phabricator.wikimedia.org/T256859)

### CODE REVIEW

**Comment by wiese** [comment]
Should wait for #41

**Comment by tzhelyazkova** [comment]
> Should wait for #41

oh :ok:

**Comment by wiese** [comment]
> The duration table changes cell size when the transition rectangle is hovered..but only sometimes.

Yes. That's my sloppy job on the presenter. The width becomes smaller so that you don't hover it anymore which in turn stops the transition.

**Comment by wiese** [comment]
> Should wait for #41

Done

**Pull request merged**
