### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by tzhelyazkova**
A fresh `npm install` inside the `vue-components` folder on `master` generates changes in `package-lock.json`.

### CODE REVIEW

**Review by micgro42 — APPROVED** [review]
Out of curiosity: Did you use the Docker container for this or you local node/npm? If the local one, then what is your node version?

We occasionally have some issues with some changes to package-lock.json that looks like some dependencies of dependencies being moved around but not actually changed.

**Comment by tzhelyazkova** [comment]
> Out of curiosity: Did you use the Docker container for this or you local node/npm? If the local one, then what is your node version?

I ran it locally. 
I did try it with docker as well, but since that has to be executed from the root folder it only installs packages based on the root package.json, right? It audits 758 packages.
If I do the same in `/vue-components` it audits 3130.

> We occasionally have some issues with some changes to package-lock.json that looks like some dependencies of dependencies being moved around but not actually changed.

Hmm, interesting. I looked at the package-lock before opening this and seems like it's legit changes, like packages being removed. :woman_shrugging:

**Comment by tzhelyazkova** [comment]
> Out of curiosity: Did you use the Docker container for this or you local node/npm? If the local one, then what is your node version?

I ran it locally. 
I did try it with docker as well, but since that has to be executed from the root folder it only installs packages based on the root package.json, right? It audits 758 packages.
If I do the same in `/vue-components` it audits 3130.

> We occasionally have some issues with some changes to package-lock.json that looks like some dependencies of dependencies being moved around but not actually changed.

Hmm, interesting. I looked at the package-lock before opening this and seems like it's legit changes, like packages being removed. :woman_shrugging:

**Comment by itamargiv** [comment]
What strikes me as particularly odd is that the tokens dependency is excluded.. I would think that running `lerna bootstrap` from root would ensure these are installed properly...

**Pull request merged**
