### PR TITLE
refactor: extract core of LookupComponent

### PR DESCRIPTION
**Pull request by micgro42**
We'll need that core in the QuantityInput component.

### CODE REVIEW

**Comment by Ladsgroup** [comment]
LookupCore sounds vague. Can it be LookupInput instead?

**Comment by micgro42** [comment]
> LookupCore sounds vague. Can it be LookupInput instead?

The name is certainly open for improvement. But it is not only the Input, but also the OptionsMenu. My first working title was `InputAndMenu`, not great either.

More suggestions/ideas welcome.

**Comment by micgro42** [comment]
@wmde/wmde-wikidata-ds This is now ready for review. Happy to see better ideas for the name

**Review by Ladsgroup — DISMISSED** [review]

**Comment by jakobw** [comment]
I agree with Amir that `LookupInput` gives a better idea of what it is, even if it is technically an input + a menu. Any concise name ends up being synonymous with Lookup in some way which would also be confusing.

**Comment by micgro42** [comment]
I still find `LookupCore` more descriptive and accurate than `LookupInput`, but I'll yield to the larger number of voices saying otherwise and have renamed it accordingly.

**Review by bereket-WMDE — DISMISSED** [review]
The PR looks good so far.
as far as the name goes, I think `Lookupcore` is the better choice. but its too late now, since its has been renamed.
I'm sure someone in the future, who's consuming Wikit, will raise this issue up :)

**Review by Ladsgroup — APPROVED** [review]

**Pull request merged**
