### PR TITLE
Bump version to 2.0.0-alpha.0

### PR DESCRIPTION
**Pull request by Ladsgroup**
We need the new version in query builder, it's currently blocking lots
of work.

### CODE REVIEW

**Comment by itamargiv** [comment]
Then next version would be `2.0.0-alpha.0` since we merged breaking changes into the master. Also, let me know when you have time, so we can do a one off r4elease together (the pre-release process is a little different than the release process we currently have (I am working on creating documentation and new workflows fro the pre-release).

**Comment by Ladsgroup** [comment]
> Then next version would be `2.0.0-alpha.0` since we merged breaking changes into the master. Also, let me know when you have time, so we can do a one off r4elease together (the pre-release process is a little different than the release process we currently have (I am working on creating documentation and new workflows fro the pre-release).

I might be missing something obvious but the flavor change for buttons didn't get merged. Did we merge something else?

**Comment by itamargiv** [comment]
> Did we merge something else?

Yeah, we deprecated the width prop for all components (#259). You can also take a look at `[CHANGELOG.md](https://github.com/wmde/wikit/blob/master/CHANGELOG.md)` to see the next expected version and what changed.

**Comment by Ladsgroup** [comment]
> > Did we merge something else?
> 
> Yeah, we deprecated the width prop for all components (#259). You can also take a look at [`CHANGELOG.md`](https://github.com/wmde/wikit/blob/master/CHANGELOG.md) to see the next expected version and what changed.

Thanks. Done now.

**Review by itamargiv — APPROVED** [review]
Thank you!

**Pull request merged**
