### PR TITLE
Use node12

### PR DESCRIPTION
**Pull request by Ladsgroup**
Bug: T285670

### CODE REVIEW

**Comment by Ladsgroup** [comment]
Not 100% sure it works in all aspects. Double checking tomorrow.

**Comment by micgro42** [comment]
You selected Node12, i.e. Maintenance LTS, would it also work with Node14, i.e. Active LTS?

I think using the nodejs docker images from DockerHub would be fine. Those releng images aren't meant for dev environments anyway.

**Comment by micgro42** [comment]
After talking about this a bit more in the daily today:

As long as the (major) node version in the developer image and CI is consistent, we should be fine to increase this to 14. Applications that use this library via npm will always use the already compiled code, not the dev dependencies of Wikit.

That being said, we will also want to update the dev images of Query Builder, Wikidata Bridge and others. But those should probably be consistent with is used in their CI and on WMF Jenkins that is Node.js v12.

That being said, we _can_ do that in two steps/commits and merge this PR from v10 to v12 now and open another one for making the step from v12 to v14.

**Review by micgro42 — DISMISSED** [review]
If we end up sticking to this way of providing Node.js v12, then I'd recommend renaming the service in docker-compose.yml from `node` to `npm`, because that will let us run commands like `docker-compose run --rm --user=$(id -u):$(id -g) npm audit` which is much less confusing than the messing with entry point in this patch.

But that should probably be a follow-up. Because if we switch to Node.js v14 after all, then we do not want that.

**Comment by Ladsgroup** [comment]
> If we end up sticking to this way of providing Node.js v12, then I'd recommend renaming the service in docker-compose.yml from `node` to `npm`, because that will let us run commands like `docker-compose run --rm --user=$(id -u):$(id -g) npm audit` which is much less confusing than the messing with entry point in this patch.
> 
> But that should probably be a follow-up. Because if we switch to Node.js v14 after all, then we do not want that.

All of these gymnastics were needed because the releng docker file was different than the production one, I just reverted to use the dockerhub image and the changes are pretty minimal here.

**Comment by micgro42** [comment]
> > If we end up sticking to this way of providing Node.js v12, then I'd recommend renaming the service in docker-compose.yml from `node` to `npm`, because that will let us run commands like `docker-compose run --rm --user=$(id -u):$(id -g) npm audit` which is much less confusing than the messing with entry point in this patch.
> > But that should probably be a follow-up. Because if we switch to Node.js v14 after all, then we do not want that.
> 
> All of these gymnastics were needed because the releng docker file was different than the production one, I just reverted to use the dockerhub image and the changes are pretty minimal here.

Looks good, but now the `package-lock.json` needs to be regenerated, because this Node.js v12 image contains npm 6 again.

**Comment by Ladsgroup** [comment]
> Looks good, but now the `package-lock.json` needs to be regenerated, because this Node.js v12 image contains npm 6 again.

Thanks. Done now.

**Review by micgro42 — APPROVED** [review]

**Pull request merged**
