### PR TITLE
Let extra Lookup attributes fall trough to the <input>

### PR DESCRIPTION
**Pull request by micgro42**
Bug: T322686

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
Looks good to me, but in #538/#540 we made the change on master and then cherry-picked it to next – should we cherry-pick this back to master as well?

Also, I’d like to see some tests for this; but since we didn’t add any tests for `TextInput` either, we can do that in a separate PR and add tests for both components at once there. (And if it doesn’t work out for some reason, it doesn’t block this PR.)

Not sure what to do about ui-review :/

**Comment by micgro42** [comment]
UI review is happy now after I fixed it on the `next` branch. I made a retro note about it.

I'll look into adding a test.

Should we drop the `aria-required` prop and let it now be handled by the arg binding?

Backporting it to master is the plan :+1:

**Comment by lucaswerkmeister** [comment]
> Should we drop the `aria-required` prop and let it now be handled by the arg binding?

I like that idea – it should even double as a test for this feature, since we have an existing test that the `<input>` ends up with an `aria-required` attribute :)

**Comment by sai-san** [comment]
> UI review is happy now after I fixed it on the `next` branch. I made a retro note about it.
> 
> I'll look into adding a test.
> 
> Should we drop the `aria-required` prop and let it now be handled by the arg binding?
> 
> Backporting it to master is the plan 👍

I approved the UI changes in the relevant Chromatic build. Weird enough, it was complaining about spacing changes in the Icon component page.

**Comment by micgro42** [comment]
> I approved the UI changes in the relevant Chromatic build some minutes ago. Weird enough, it was complaining about spacing changes in the Icon component page.

Ah, thank you! I hadn't noticed that! I thought my clicking all the buttons had worked eventually, but apparently it didn't  😅

Test has been added :)

**Comment by micgro42** [comment]
> I like that idea – it should even double as a test for this feature, since we have an existing test that the `<input>` ends up with an `aria-required` attribute :)

* [ ]  TODO for tomorrow 👆

**Comment by micgro42** [comment]
Done. Should be ready for another review :)

**Review by lucaswerkmeister — APPROVED** [review]
I thought we were going to keep the `ariaRequired` tests and only add the new test in a separate change, but okay ^^ I tested locally that the old tests also still pass if they’re added back.

**Comment by micgro42** [comment]
> I thought we were going to keep the `ariaRequired` tests and only add the new test in a separate change, but okay ^^ I tested locally that the old tests also still pass if they’re added back.

I considered it, but judged it to be more noise than what is worth it. These tests implied that there is indeed an aria-required prop. So I merged the test that previously added `aria-required: true` into the new test, and dropped the one that just asserted the default behavior.

**Pull request merged**
