### PR TITLE
Add keyboard navigation handlers for popover component

### PR DESCRIPTION
**Pull request by Ladsgroup**
Bug: [T277738](https://phabricator.wikimedia.org/T277738)

### CODE REVIEW

**Review by lucaswerkmeister — COMMENTED** [review]
Seems to work fine, though I left a comment on the task asking about `Space` events.

Can we have some tests for this? (There are some similar tests in `vue-components/tests/unit/components/Popover.spec.ts` already, so I think unit tests should be fine, though browser tests would probably also be an option.)

**Comment by SaiSan-WMDE** [comment]
> Seems to work fine, though I left a comment on the task asking about `Space` events.
> 
> As mentioned in Phabricator, I overlooked the need to make the popover dismissable by pressing `space` while the focus is still on its trigger. Sorry abou that, @Ladsgroup.

**Comment by Ladsgroup** [comment]
> > Seems to work fine, though I left a comment on the task asking about `Space` events.
> 
> As mentioned in Phabricator, I overlooked the need to make the popover dismissable by pressing `space` while the focus is still on its trigger. Sorry about that, @Ladsgroup.

Done!

**Review by SaiSan-WMDE — APPROVED** [review]
LGTM! The popover's behavior meets the AC 👍

**Review by lucaswerkmeister — APPROVED** [review]

**Pull request merged**
