### PR TITLE
Improve github workflows 

### PR DESCRIPTION
**Pull request by itamargiv**
This PR aims to improve GH workflows by:

* Splitting our main push workflow into separate jobs
* Conditionally running jobs depending on path filter groups (visual -> deploy storybook, behavioral -> run e2e)
* Running all jobs on merge to master
* Caching node modules and dist to speed up bootstrapping
* Ensuring token changes trigger storybook deployment
* Allowing tests to run on all changes (will help enforce up to date branch policy)
* Remove unnecessary duplicate workflow

**NB**: This PR was validated throughout by adding noop commits in the `docs`, `token` and `vue-components` folders. Feel free to create commits in those respective folder to test out the conditional jobs in the workflow.

Issue: [T266460](https://phabricator.wikimedia.org/T266460)
Issue: [T264446](https://phabricator.wikimedia.org/T264446)

### CODE REVIEW

**Comment by micgro42** [comment]
Looks fancy! Though, I'm not entirely familiar with the DS CI setup, so I'd rather give someone from the original crew the chance to chime in.

I noticed [T264446](https://phabricator.wikimedia.org/T264446) states:

> Make sure that the branch is up-to-date before merging

Is that implemented here or is this just step on the way there?

**Comment by itamargiv** [comment]
> Is that implemented here or is this just step on the way there?

It is a step, after this is merged we will make the "Test and deploy / setup" and "Test and Deploy / test" checks  mandatory before merging to master, which will re-enable the "Make sure that the branch is up-to-date" option.

Screenshot from 2020-11-10 14-43-44

**Comment by micgro42** [comment]
> > Is that implemented here or is this just step on the way there?
> 
> It is a step, after this is merged we will make the "Test and deploy / setup" and "Test and Deploy / test" checks mandatory before merging to master, which will re-enable the "Make sure that the branch is up-to-date" option.
> 
> Screenshot from 2020-11-10 14-43-44

Oh wow, I wasn't aware that this is possible by now. This is pretty awesome!

/me makes note for adjustments to make to the query-builder repository.

**Review by tzhelyazkova — APPROVED** [review]
Looks great!
Caching node modules and dist is a nice touch, but I'm afraid most time-consuming processes are actually the Chromatic deployment and the e2e cross browser testing.

**Comment by tzhelyazkova** [comment]
> Looks fancy! Though, I'm not entirely familiar with the DS CI setup, so I'd rather give someone from the original crew the chance to chime in.

I think it's also important to get the opinion of the Query Builder peeps because you're currently the ones contributing component after component to WiKit and having to work with this CI setup.

**Comment by itamargiv** [comment]
> Caching node modules and dist is a nice touch, but I'm afraid most time-consuming processes are actually the Chromatic deployment and the e2e cross browser testing.

Actually yeah, I noticed that, I think we can cut the chromatic deployment shorter by about 2:30 mins if we properly cache also the storybooks, but that requires a bit more effort, see [comment on taskT266460](https://phabricator.wikimedia.org/T266460#6615841). Unfortunately, I don't think there's much to be done about the e2e tests though, at least I don't have any ideas at the moment.

**Review by micgro42 — APPROVED** [review]
Looks good to me, curious to see how it will play out in practice

**Pull request merged**
