### PR TITLE
Update wikimedia base UI

### PR DESCRIPTION
**Pull request by zonzon1804**
Update wikimedia base UI from 0.18.0 to 0.19.0

### CODE REVIEW

**Review by tzhelyazkova — CHANGES_REQUESTED** [review]
The package `wikimedia-ui-base` provides most of the values for WiKit's design tokens. Therefore we depend on it only for the `tokens` package.

For inspiration, here is the PR #281 where the last update of that package happened.
For more info about the different packages within WiKit see https://wmde.github.io/wikit/?path=/story/documentation-decisions-and-adrs-overview--page#packages
For more info on how this package relates to our design tokens see this ADR https://wmde.github.io/wikit/?path=/story/documentation-decisions-and-adrs-adrs-3-design-token-agnosticism-and-tooling--page#3-design-token-agnosticism-and-tooling
For more info on how we manage the different packages within this repo, see this ADR https://wmde.github.io/wikit/?path=/story/documentation-decisions-and-adrs-adrs-4-use-a-monorepo--page

**Comment by lucaswerkmeister** [comment]
The latest version is still adding the package to the root `package.json`, as far as I can tell, which probably shouldn’t happen. (Also, there’s a strange unrelated diff in the `vue-components` tests?)

**Comment by zonzon1804** [comment]
saw that... didn't notice. Right away

**Review by lucaswerkmeister — CHANGES_REQUESTED** [review]
It still looks like the change does more than it’s supposed to:

- `docs/package-lock.json` has changes that look unrelated
- `package-lock.json` still has wikimedia-ui-base
- `tokens/package-lock.json` updates wikimedia-ui-base but also has other changes that look unrelated
- `vue-components/package-lock.json` has a huge diff that GitHub won’t even render, but that I assume must also be unrelated?
- `vue-components/tests/e2e/specks/Lookup.test.js` has changes that also look unrelated

**Comment by Ladsgroup** [comment]
Maybe I'm wrong but if you don't use the right npm version, it'll mess up the package lock files. My suggestion is to use the docker commands mentioned in the README. I'm sorry if you followed it and this is not the problem.

**Comment by zonzon1804** [comment]
it could be, npm is stuck with 6.14.4. Lemme check it out

**Review by lucaswerkmeister — APPROVED** [review]

**Comment by zonzon1804** [comment]
Anyone knows why the browser-tests is skipped? Would it be just the beauty of running stuff on a cloud computer or something wrong with the code?

**Comment by tzhelyazkova** [comment]
> Anyone knows why the browser-tests is skipped? Would it be just the beauty of running stuff on a cloud computer or something wrong with the code?

The browser tests are configured to run only on changes in the package `vue-components` since it doesn't make sense to run for `tokens` and `docs` as there are no components there.

**Review by tzhelyazkova — APPROVED** [review]

**Pull request merged**
